version: "3.8"

services:
  # Redis - shared by all microservices
  redis:
    image: redis:7-alpine
    container_name: realworld-redis-qa
    ports:
      - "6380:6379"
    volumes:
      - redis_data_qa:/data
    command: redis-server --appendonly yes
    networks:
      - realworld-network-qa

  # Redis Insight - GUI for Redis
  redis-insight:
    image: redis/redisinsight:2.68.0
    container_name: realworld-redis-insight-qa
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_qa:/db
    environment:
      - REDIS_INSIGHT_PORT=8001
      - REDIS_INSIGHT_HOST=0.0.0.0
    networks:
      - realworld-network-qa
    depends_on:
      - redis

  # PostgreSQL databases - separate for each microservice
  postgres-api-gateway:
    image: postgres:15-alpine
    container_name: realworld-postgres-api-gateway-qa
    environment:
      POSTGRES_DB: api_gateway_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_api_gateway_qa:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network-qa

  postgres-orders:
    image: postgres:15-alpine
    container_name: realworld-postgres-orders-qa
    environment:
      POSTGRES_DB: orders_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"
    volumes:
      - postgres_orders_qa:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network-qa

  postgres-products:
    image: postgres:15-alpine
    container_name: realworld-postgres-products-qa
    environment:
      POSTGRES_DB: products_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - postgres_products_qa:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network-qa

  postgres-users:
    image: postgres:15-alpine
    container_name: realworld-postgres-users-qa
    environment:
      POSTGRES_DB: users_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5445:5432"
    volumes:
      - postgres_users_qa:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network-qa

  # Microservices
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: production
    container_name: realworld-api-gateway-qa
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: qa
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-api-gateway
      POSTGRES_PORT: 5432
      POSTGRES_DB: api_gateway_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-api-gateway
    networks:
      - realworld-network-qa

  orders-service:
    build:
      context: .
      dockerfile: apps/orders-service/Dockerfile
      target: production
    container_name: realworld-orders-service-qa
    ports:
      - "4001:3001"
    environment:
      NODE_ENV: qa
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-orders
      POSTGRES_PORT: 5432
      POSTGRES_DB: orders_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-orders
    networks:
      - realworld-network-qa

  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
      target: production
    container_name: realworld-product-service-qa
    ports:
      - "4002:3002"
    environment:
      NODE_ENV: qa
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-products
      POSTGRES_PORT: 5432
      POSTGRES_DB: products_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-products
    networks:
      - realworld-network-qa

  users-service:
    build:
      context: .
      dockerfile: apps/users-service/Dockerfile
      target: production
    container_name: realworld-users-service-qa
    ports:
      - "4003:3003"
    environment:
      NODE_ENV: qa
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-users
      POSTGRES_PORT: 5432
      POSTGRES_DB: users_qa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-users
    networks:
      - realworld-network-qa

volumes:
  redis_data_qa:
  redis_insight_qa:
  postgres_api_gateway_qa:
  postgres_orders_qa:
  postgres_products_qa:
  postgres_users_qa:

networks:
  realworld-network-qa:
    driver: bridge
