version: "3.8"

services:
  # Redis - shared by all microservices
  redis:
    image: redis:7-alpine
    container_name: realworld-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    networks:
      - realworld-network

  # Redis Insight - GUI for Redis
  redis-insight:
    image: redis/redisinsight:2.68.0
    container_name: realworld-redis-insight-dev
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_dev:/db
    environment:
      - REDIS_INSIGHT_PORT=8001
      - REDIS_INSIGHT_HOST=0.0.0.0
    networks:
      - realworld-network
    depends_on:
      - redis

  # PostgreSQL databases - separate for each microservice
  postgres-api-gateway:
    image: postgres:15-alpine
    container_name: realworld-postgres-api-gateway-dev
    environment:
      POSTGRES_DB: api_gateway_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_api_gateway_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network

  postgres-orders:
    image: postgres:15-alpine
    container_name: realworld-postgres-orders-dev
    environment:
      POSTGRES_DB: orders_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_orders_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network

  postgres-products:
    image: postgres:15-alpine
    container_name: realworld-postgres-products-dev
    environment:
      POSTGRES_DB: products_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_products_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network

  postgres-users:
    image: postgres:15-alpine
    container_name: realworld-postgres-users-dev
    environment:
      POSTGRES_DB: users_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_users_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - realworld-network

  # Microservices
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: production
    container_name: realworld-api-gateway-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-api-gateway
      POSTGRES_PORT: 5432
      POSTGRES_DB: api_gateway_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-api-gateway
    networks:
      - realworld-network

  orders-service:
    build:
      context: .
      dockerfile: apps/orders-service/Dockerfile
      target: production
    container_name: realworld-orders-service-dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-orders
      POSTGRES_PORT: 5432
      POSTGRES_DB: orders_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-orders
    networks:
      - realworld-network

  product-service:
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
      target: production
    container_name: realworld-product-service-dev
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-products
      POSTGRES_PORT: 5432
      POSTGRES_DB: products_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-products
    networks:
      - realworld-network

  users-service:
    build:
      context: .
      dockerfile: apps/users-service/Dockerfile
      target: production
    container_name: realworld-users-service-dev
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres-users
      POSTGRES_PORT: 5432
      POSTGRES_DB: users_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
      - postgres-users
    networks:
      - realworld-network

volumes:
  redis_data_dev:
  redis_insight_dev:
  postgres_api_gateway_dev:
  postgres_orders_dev:
  postgres_products_dev:
  postgres_users_dev:

networks:
  realworld-network:
    driver: bridge
